apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-dev
  namespace: argocd
  finalizers: []
spec:
  project: default
  source:
    repoURL: https://github.com/HarrisonZz/chatbot-devops-demo.git
    targetRevision: main
    path: k8s/argocd/apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
