apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # 先套平台
spec:
  project: platform
  source:
    repoURL: https://github.com/HarrisonZz/chatbot-devops-demo.git
    targetRevision: main
    path: k8s/platform/external-secrets
  destination:
    server: https://github.com/HarrisonZz/chatbot-devops-demo.git
    namespace: external-secrets         # (如果你 ESO 裝在這個 ns；純 ClusterSecretStore 不依賴 ns 也可)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
