apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # 先套平台
spec:
  project: platform
  source:
    repoURL: https://github.com/HarrisonZz/chatbot-devops-demo.git
    targetRevision: main
    path: k8s/platform/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets         # (如果你 ESO 裝在這個 ns；純 ClusterSecretStore 不依賴 ns 也可)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  clusterResourceWhitelist:
  # 1. 允許建立 Namespace
  - group: ''
    kind: Namespace
  # 2. 允許建立 ClusterSecretStore (如果你的 Git 裡有用的話)
  - group: 'external-secrets.io'
    kind: ClusterSecretStore
  # 3. 如果你有用 ClusterExternalSecret，也要加
  - group: 'external-secrets.io'
    kind: ClusterExternalSecret
