apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-chatbot-dev
resources:
  - ssm_ext_secret.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
