apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssm_ext_secret.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - otel_instrumentation.yaml
