apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-chatbot-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: ai-chatbot-config
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFRONT_STATIC_URL
      remoteRef:
        key: /ai-chatbot/dev/cloudfront_url