apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ai-chatbot-prod

images:
  - name: 533267110761.dkr.ecr.ap-northeast-1.amazonaws.com/ai-chatbot-app-dev
    newTag: v1.0.0

patches:
  - path: patch-deploy.yaml
  - path: patch-ingress.yaml
