apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-chatbot-ingress
  annotations:
    # 這裡會與 Base 的 annotations 合併
    external-dns.alpha.kubernetes.io/hostname: www.hrscyj.uk
    alb.ingress.kubernetes.io/load-balancer-name: ai-chatbot-alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:533267110761:certificate/dcaf49fa-599c-4046-8bc0-4fee782ef8be
spec:
  rules:
    - host: www.hrscyj.uk # 修正這裡的 Host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-chatbot-service
                port:
                  number: 80