---
collections:
  - name: amazon.aws
    version: "==10.1.2"
  - name: community.aws
    version: "==10.0.0"
  - name: kubernetes.core
    version: "==6.2.0"
  - name: community.docker
    version: "==5.0.4"
  - name: community.general
    version: "==12.1.0"
